### ISSUE TITLE
pissed off!

### ISSUE THREAD

**Issue by jamieduk** [faizanahemad/data-science-utils#1]
your stupid asf nothing here for pythn its hidden what a moron waste of my time ps no1 cares about indian prices for bs cars i want uk prices for oil thats it and the pythion that will get that! better yet i need a bash script to do this and get around all the random bs on pages to stop live prices all i want is just the current oil prices for bp so i can make data lists! then i can make charts but noone seems to want oil prices out there except those that actually trade init!

**Comment by jamieduk** [comment]
your stupid asf nothing here for python its hidden what a moron waste of my time ps no1 cares about indian prices for bs cars i want uk prices for oil thats it and the python that will get that! better yet i need a bash script to do this and get around all the random bs on pages to stop live prices all i want is just the current oil prices for bp so i can make data lists! then i can make charts but noone seems to want oil prices out there except those that actually trade init!

**Comment by faizanahemad** [comment]
Highly irrelevant and disrespectful. Also no context on what this person is trying to find. Closed.
